### ISSUE TITLE
Use spark for forecast

### ISSUE THREAD

**Issue by bpinto** [oh-my-fish/plugin-weather#1]
May I suggest a feature?

We could use [spark](https://github.com/holman/spark) for displaying the forecast.

```
spark 0 30 55 80 33 150
▁▂▃▅▂▇
```

Would be super great to convert the plugin from bash to fish and use it as a dependency here. What do you say?

**Comment by sagebind** [comment]
Never heard of spark before. That's wicked cool! I'll see what I can do.

**Comment by sagebind** [comment]
Spark looks pretty active -- it seems a little counter-productive to rewrite it in fish. Would a bash dependency be OK? A git submodule could be used for that.

**Comment by bpinto** [comment]
I wouldn't call a project whose last commit on the code was done on May 27, 2014 active. But, if you think that using a bash dependency is better, I'm okay.

Not sure if we should use git submodule though, it seems awkward. Maybe you need to make sure people install spark before they can use this feature?

P.S.: I think converting is still the best option. :dancers:

**Comment by sagebind** [comment]
Shark, the existing Spark port from @bucaran was just ported to the OMF package repository today, so I can release the new features now. Enjoy! :poultry_leg:
