### ISSUE TITLE
What is '/tmp/MD5 ?

### ISSUE THREAD

**Issue by ghost** [oh-my-fish/plugin-weather#12]
@coderstephen Nice use of shark, do check the updated version, which should finish the initial argv parsing in less than a millisecond.

To the issue. Here is what I am getting:

```
An error occurred while redirecting file '/tmp/MD5 ("http://geoip.nekudo.com/api/122.134.148.246") = a0fdcf61261d87dbd1f23de895ffcbed.url'
open: No such file or directory
Array index out of bounds
~/.config/.../functions/weather.fish (line 1): weather.fetch "http://api.openweathermap.org/data/2.5/weather" lat=$location[1] lon=$location[2] APPID=$weather_api_key
                                                                                                                                                   ^
in command substitution
    called on line 0 of file ~/.config/.../functions/weather.fish

in function 'weather'
    called on standard input

Unable to fetch weather data; please try again later.
```

**Comment by sagebind** [comment]
It is supposed to store cached weather data in `/tmp`, but it looks like the file name it chose was bad (`/tmp/MD5 ("http://geoip.nekudo.com/api/122.134.148.246") = a0fdcf61261d87dbd1f23de895ffcbed.url`). The correct file name should be `a0fdcf61261d87dbd1f23de895ffcbed.url`.

It generates an MD5 sum of the URL being cached so it knows how to retrieve it later specific to location.

There must be a bug in the MD5 generator. What OS are you using?

> do check the updated version, which should finish the initial argv parsing in less than a millisecond.

Awesome! Will do.

**Comment by ghost** [comment]
I am using OS X El Capitan.

**Comment by sagebind** [comment]
OK. I think I messed up the command line flags order for the BSD `md5` utility. I (hopefully) fixed the issue on `master`. Could you update and check if it fixes the issue?

**Comment by sagebind** [comment]
This should be fixed now that hashing is done by the `hash` plugin. If you have more issues with the md5 being produced, feel free to reopen.
