### ISSUE TITLE
Wind info prints out garbled

### ISSUE THREAD

**Issue by vredesbyyrd** [oh-my-fish/plugin-weather#18]
I was taking a look at the code in weather.fish to see if i could get the wind to display in km/h rather than m/s, and instead I discovered that when printing out 'wind gust' speed, the output is all messed up. I cant figure out why. 

I commute daily by bike, and have been looking for a simple cli tool to print out detailed wind info. Your script reports exactly the info i want, without a bunch of garbage info i do not need. I would love to get it working. Any tips on what could be going wrong here would be very appreciated.

    ~fish 2.7.1-1
    ~jq 1.5-6
    ~Linux kernel 4.16.3-1 - arch 

![screenshot from 2018-04-26 14-18-38](https://user-images.githubusercontent.com/22080838/39328091-cd10c4de-495f-11e8-8bdc-f7d5a5f3891d.png)

**Comment by mojotx** [comment]
This should now be resolved. 🙂

**Comment by vredesbyyrd** [comment]
Awesome. Good to hear. Just gave the new code a test drive and works great. Thanks :)
