### ISSUE TITLE
Have dig command use system DNS

### ISSUE THREAD

**Issue by rrosson** [oh-my-fish/plugin-weather#2]
Various networks do not allow dig lookups to outside DNS servers. Would it be possible to change line 9 in the code to use local configured DNS?

<current code>
if not set ip (dig +short myip.opendns.com @resolver1.opendns.com)

<suggested code>
if not set ip (dig +short myip.opendns.com)

**Comment by sagebind** [comment]
I like the idea, but `dig +short myip.opendns.com` gives me no result on my system. How do you query the default DNS?

**Comment by sagebind** [comment]
An alternative would be to use a web-based service like http://ipecho.net. That might be more consistent, but a little slower and not as reliable.

**Comment by sagebind** [comment]
Does [plugin-weather/better-ips](https://github.com/oh-my-fish/plugin-weather/tree/better-ips) work better for you?

``` fish
$ omf update
$ omf cd weather
$ git fetch origin better-ips
$ git checkout better-ips
```

**Comment by rrosson** [comment]
when I do it I get my external IP address. My internal DNS server uses OpenDNS as a forwarder.  :) Not sure if that makes a difference. How about adding an or in there and check using local dos first if nothing is returned use resolver.opendns.org. I think using an external web service might be blocked due to information leakage (paranoid people)

**Comment by sagebind** [comment]
> when I do it I get my external IP address

That's a good thing. Geolocation only works if it knows your actual public IP.

> I think using an external web service might be blocked due to information leakage (paranoid people)

Well, the weather data is fetched from an external web service anyway, so those people wouldn't want to use the plugin anyway. :)

**Comment by rrosson** [comment]
My host OS is OS X 10.11 so it is using whatever is in my resolv.conf when I do not append @<dns server>

Any UNIX based system should work with dig +short myip.opendns.com

**Comment by sagebind** [comment]
I'm on Ubuntu 15.04, and `dig +short myip.opendns.com` gives me no output. I haven't customized `resolv.conf` whatsoever and it contains whatever the default values are.

**Comment by rrosson** [comment]
It (dig +short myip.opendns.com) works on my ubuntu system running 14.04.3 LTS. My ubuntu system is using static IP but /etc/resolv.conf is still being generated by resolvconf..

**Comment by sagebind** [comment]
OK. I updated to use `dig` when configured with a default resolver, or fall back to a web service. Let me know if this works for you.

``` fish
$ omf update
```

**Comment by rrosson** [comment]
Ummm Looks like that did not get committed in the weather but is committed in better-ops

works perfect using the better-ops branch

**Comment by sagebind** [comment]
Sorry for the delay. It took me a day to remember to merge into master. You can switch back to master now.
